import { Load, Vehicle, Shipper } from "./types";

export const mockLoads: Load[] = [
  {
    id: "1",
    loadNumber: "LD-2024-001",
    shipperId: "SH-001",
    shipperName: "Bharat Logistics Pvt Ltd",
    origin: {
      address: "Plot 45, MIDC Industrial Area",
      city: "Mumbai",
      state: "Maharashtra",
      zipCode: "400001",
    },
    destination: {
      address: "Sector 18, Industrial Hub",
      city: "Delhi",
      state: "Delhi",
      zipCode: "110001",
    },
    pickupDate: new Date("2024-11-20"),
    pickupTime: "10:00 AM",
    deliveryDate: new Date("2024-11-25"),
    deliveryTime: "03:00 PM",
    estimatedDeliveryDate: new Date("2024-11-25"),
    cargo: {
      category: "Electronics & Technology",
      type: "Consumer Electronics",
      weight: 15000,
      volume: 2000,
      quantity: 250,
      packagingType: "Palletized Boxes",
      specialRequirements: ["Temperature Controlled", "Fragile", "Handle with Care"],
    },
    distance: 1450,
    estimatedDuration: "24-26 hours",
    contactPerson: {
      pickup: {
        name: "Ramesh Patel",
        phone: "+91-98765-11111",
      },
      delivery: {
        name: "Sunil Kumar",
        phone: "+91-98765-22222",
      },
    },
    instructions: {
      pickup: "Loading dock available from 8 AM to 6 PM. Please bring loading equipment.",
      delivery: "Delivery must be scheduled 24 hours in advance. Unloading assistance available.",
      handling: "Keep packages upright. Do not stack more than 3 pallets high.",
    },
    vehicleRequirements: {
      bodyType: "closed-body",
      size: "32 ft",
      capacity: "20 Ton",
    },
    status: "in-transit",
    assignedTruck: "TMTRK1001",
    assignedDriver: "Rajesh Kumar",
    revenue: 350000,
    documents: [
      {
        id: "DOC-001",
        name: "Bill of Lading",
        type: "PDF",
        url: "/documents/bol-001.pdf",
        uploadedAt: new Date("2024-11-19"),
      },
      {
        id: "DOC-002",
        name: "Packing List",
        type: "PDF",
        url: "/documents/packing-001.pdf",
        uploadedAt: new Date("2024-11-19"),
      },
    ],
    trackingUpdates: [
      {
        id: "TRK-001",
        timestamp: new Date("2024-11-20T08:00:00"),
        location: "Mumbai, Maharashtra",
        status: "Picked up",
        notes: "Load picked up successfully",
      },
      {
        id: "TRK-002",
        timestamp: new Date("2024-11-22T14:30:00"),
        location: "Surat, Gujarat",
        status: "In Transit",
        notes: "Passing through checkpoint",
      },
    ],
  },
  {
    id: "2",
    loadNumber: "LD-2024-002",
    shipperId: "SH-002",
    shipperName: "Express Transport Solutions",
    origin: {
      address: "Whitefield Tech Park",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560066",
    },
    destination: {
      address: "Banjara Hills Commercial Complex",
      city: "Hyderabad",
      state: "Telangana",
      zipCode: "500034",
    },
    pickupDate: new Date("2024-11-22"),
    pickupTime: "08:00 AM",
    deliveryDate: new Date("2024-11-27"),
    deliveryTime: "02:00 PM",
    estimatedDeliveryDate: new Date("2024-11-27"),
    cargo: {
      category: "Industrial Equipment",
      type: "Heavy Machinery Parts",
      weight: 25000,
      volume: 3500,
      quantity: 15,
      packagingType: "Wooden Crates",
    },
    distance: 580,
    estimatedDuration: "10-12 hours",
    vehicleRequirements: {
      bodyType: "flatbed",
      size: "40 ft",
      capacity: "25 Ton",
    },
    status: "confirmed",
    assignedTruck: "TMTRK1002",
    assignedDriver: "Amit Sharma",
    revenue: 480000,
    documents: [],
    trackingUpdates: [],
  },
  {
    id: "3",
    loadNumber: "LD-2024-003",
    shipperId: "SH-001",
    shipperName: "Bharat Logistics Pvt Ltd",
    origin: {
      address: "Salt Lake Sector V",
      city: "Kolkata",
      state: "West Bengal",
      zipCode: "700091",
    },
    destination: {
      address: "Viman Nagar",
      city: "Pune",
      state: "Maharashtra",
      zipCode: "411014",
    },
    pickupDate: new Date("2024-11-18"),
    pickupTime: "09:30 AM",
    deliveryDate: new Date("2024-11-23"),
    deliveryTime: "11:00 AM",
    estimatedDeliveryDate: new Date("2024-11-23"),
    cargo: {
      category: "Textiles & Apparel",
      type: "Garment Fabrics",
      weight: 18000,
      volume: 2800,
      quantity: 500,
      packagingType: "Fabric Rolls",
    },
    distance: 1850,
    estimatedDuration: "28-30 hours",
    vehicleRequirements: {
      bodyType: "container",
      size: "20 ft",
      capacity: "15 Ton",
    },
    status: "delivered",
    assignedTruck: "TMTRK1003",
    assignedDriver: "Suresh Patel",
    revenue: 420000,
    documents: [],
    trackingUpdates: [],
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    truckNumber: "TMTRK1001",
    licensePlate: "MH-02-AB-1234",
    type: "refrigerated",
    capacity: {
      weight: 20000,
      volume: 2500,
    },
    status: "in-transit",
    assignedDriver: {
      id: "D-001",
      name: "Rajesh Kumar",
      phone: "+91-98765-43210",
      email: "rajesh.kumar@freight.com",
      licenseNumber: "DL-0320230012345",
      rating: 4.8,
    },
    lastMaintenance: new Date("2024-10-15"),
    nextMaintenance: new Date("2024-12-15"),
    fuelEfficiency: 6.5,
    yearManufactured: 2022,
  },
  {
    id: "2",
    truckNumber: "TMTRK1002",
    licensePlate: "KA-01-CD-5678",
    type: "dry-van",
    capacity: {
      weight: 30000,
      volume: 4000,
    },
    status: "available",
    assignedDriver: {
      id: "D-002",
      name: "Amit Sharma",
      phone: "+91-98765-43211",
      email: "amit.sharma@freight.com",
      licenseNumber: "DL-0320230012346",
      rating: 4.9,
    },
    lastMaintenance: new Date("2024-11-01"),
    nextMaintenance: new Date("2025-01-01"),
    fuelEfficiency: 7.2,
    yearManufactured: 2023,
  },
  {
    id: "3",
    truckNumber: "TMTRK1003",
    licensePlate: "WB-06-EF-9012",
    type: "flatbed",
    capacity: {
      weight: 25000,
      volume: 3200,
    },
    status: "available",
    assignedDriver: {
      id: "D-003",
      name: "Suresh Patel",
      phone: "+91-98765-43212",
      email: "suresh.patel@freight.com",
      licenseNumber: "DL-0320230012347",
      rating: 4.7,
    },
    lastMaintenance: new Date("2024-10-20"),
    nextMaintenance: new Date("2024-12-20"),
    fuelEfficiency: 6.8,
    yearManufactured: 2021,
  },
];

export const mockShippers: Shipper[] = [
  {
    id: "SH-001",
    shipperId: "TM001",
    companyName: "Bharat Logistics Pvt Ltd",
    contactPerson: "Vikram Singh",
    email: "vikram.singh@bharatlogistics.in",
    phone: "+91-22-2345-6789",
    address: {
      address: "Plot 45, MIDC Industrial Area",
      city: "Mumbai",
      state: "Maharashtra",
      zipCode: "400001",
    },
    paymentTerms: "Net 30",
    totalBusinessVolume: 18500000,
    averageLoadValue: 380000,
    reliabilityScore: 95,
    rating: 4.7,
    activeLoadsCount: 12,
    totalBids: 45,
    totalRatings: 25,
    profileImage: null,
    companyRegistrationType: "Private Company",
    yearsInBusiness: "5+",
    pincode: "400001",
    noSecondPoc: false,
    namePoc: "Rahul Sharma",
    phonePoc: "+91-98765-43299",
    gstNotApplicable: false,
    gstNumber: "27AABCU9603R1ZM",
    legalName: "Bharat Logistics Pvt Ltd",
    gstCertificate: null,
    panNumber: "AABCU9603R",
    nameAsPerPan: "Vikram Singh",
    dobAsPerPan: "1985-05-15",
    panImage: null,
    profileCreatedAt: "2024-01-15 10:30:00",
    profileUpdatedAt: "2024-11-20 14:22:00",
    kycVerified: "1",
    status: "Active",
  },
  {
    id: "SH-002",
    shipperId: "TM002",
    companyName: "Express Transport Solutions",
    contactPerson: "Priya Reddy",
    email: "priya.reddy@expresstransport.in",
    phone: "+91-80-4567-8901",
    address: {
      address: "Whitefield Tech Park",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560066",
    },
    paymentTerms: "Net 45",
    totalBusinessVolume: 14200000,
    averageLoadValue: 320000,
    reliabilityScore: 88,
    rating: 4.5,
    activeLoadsCount: 8,
    totalBids: 32,
    totalRatings: 18,
    profileImage: null,
    companyRegistrationType: "Partnership",
    yearsInBusiness: "3-5",
    pincode: "560066",
    noSecondPoc: true,
    namePoc: null,
    phonePoc: null,
    gstNotApplicable: false,
    gstNumber: "29AADCE1234F1ZP",
    legalName: "Express Transport Solutions LLP",
    gstCertificate: null,
    panNumber: "AADCE1234F",
    nameAsPerPan: "Priya Reddy",
    dobAsPerPan: "1990-08-22",
    panImage: null,
    profileCreatedAt: "2024-03-10 09:15:00",
    profileUpdatedAt: "2024-11-18 11:45:00",
    kycVerified: "1",
    status: "Active",
  },
  {
    id: "SH-003",
    shipperId: "TM003",
    companyName: "North India Cargo Services",
    contactPerson: "Arjun Mehta",
    email: "arjun.mehta@nicargo.in",
    phone: "+91-11-3456-7890",
    address: {
      address: "Sector 18, Industrial Hub",
      city: "Delhi",
      state: "Delhi",
      zipCode: "110001",
    },
    paymentTerms: "Net 30",
    totalBusinessVolume: 12800000,
    averageLoadValue: 290000,
    reliabilityScore: 92,
    rating: 4.6,
    activeLoadsCount: 10,
    totalBids: 28,
    totalRatings: 15,
    profileImage: null,
    companyRegistrationType: "Sole Proprietorship",
    yearsInBusiness: "1-3",
    pincode: "110001",
    noSecondPoc: false,
    namePoc: "Sunil Kumar",
    phonePoc: "+91-98765-43300",
    gstNotApplicable: false,
    gstNumber: "07AABCN5678L1ZQ",
    legalName: "North India Cargo Services",
    gstCertificate: null,
    panNumber: "AABCN5678L",
    nameAsPerPan: "Arjun Mehta",
    dobAsPerPan: "1988-12-01",
    panImage: null,
    profileCreatedAt: "2024-02-20 12:00:00",
    profileUpdatedAt: "2024-11-19 16:30:00",
    kycVerified: "0",
    status: "Pending",
  },
];
